#!/usr/bin/env python3
"""
Generate a palette-specific plugin theme file for zsh-autosuggestions,
zsh-syntax-highlighting, and fzf — all colored from the same Catppuccin palette.

Usage:
    build-plugin-theme.py <palette> <out.zsh>

The output is sourced by .zshrc between zsh-autosuggestions (sourced earlier)
and zsh-syntax-highlighting (sourced last). `ewallis-theme` swaps the active
file when the palette changes.
"""
from __future__ import annotations
import sys
from pathlib import Path

# Catppuccin palettes — must stay in sync with build-iterm-profile.py
PALETTES = {
    "latte": {
        "rosewater": "#dc8a78", "flamingo": "#dd7878", "pink": "#ea76cb",
        "mauve": "#8839ef", "red": "#d20f39", "maroon": "#e64553",
        "peach": "#fe640b", "yellow": "#df8e1d", "green": "#40a02b",
        "teal": "#179299", "sky": "#04a5e5", "sapphire": "#209fb5",
        "blue": "#1e66f5", "lavender": "#7287fd", "text": "#4c4f69",
        "subtext1": "#5c5f77", "subtext0": "#6c6f85", "overlay2": "#7c7f93",
        "overlay1": "#8c8fa1", "overlay0": "#9ca0b0", "surface2": "#acb0be",
        "surface1": "#bcc0cc", "surface0": "#ccd0da", "base": "#eff1f5",
        "mantle": "#e6e9ef", "crust": "#dce0e8",
    },
    "frappe": {
        "rosewater": "#f2d5cf", "flamingo": "#eebebe", "pink": "#f4b8e4",
        "mauve": "#ca9ee6", "red": "#e78284", "maroon": "#ea999c",
        "peach": "#ef9f76", "yellow": "#e5c890", "green": "#a6d189",
        "teal": "#81c8be", "sky": "#99d1db", "sapphire": "#85c1dc",
        "blue": "#8caaee", "lavender": "#babbf1", "text": "#c6d0f5",
        "subtext1": "#b5bfe2", "subtext0": "#a5adce", "overlay2": "#949cbb",
        "overlay1": "#838ba7", "overlay0": "#737994", "surface2": "#626880",
        "surface1": "#51576d", "surface0": "#414559", "base": "#303446",
        "mantle": "#292c3c", "crust": "#232634",
    },
    "macchiato": {
        "rosewater": "#f4dbd6", "flamingo": "#f0c6c6", "pink": "#f5bde6",
        "mauve": "#c6a0f6", "red": "#ed8796", "maroon": "#ee99a0",
        "peach": "#f5a97f", "yellow": "#eed49f", "green": "#a6da95",
        "teal": "#8bd5ca", "sky": "#91d7e3", "sapphire": "#7dc4e4",
        "blue": "#8aadf4", "lavender": "#b7bdf8", "text": "#cad3f5",
        "subtext1": "#b8c0e0", "subtext0": "#a5adcb", "overlay2": "#939ab7",
        "overlay1": "#8087a2", "overlay0": "#6e738d", "surface2": "#5b6078",
        "surface1": "#494d64", "surface0": "#363a4f", "base": "#24273a",
        "mantle": "#1e2030", "crust": "#181926",
    },
    "mocha": {
        "rosewater": "#f5e0dc", "flamingo": "#f2cdcd", "pink": "#f5c2e7",
        "mauve": "#cba6f7", "red": "#f38ba8", "maroon": "#eba0ac",
        "peach": "#fab387", "yellow": "#f9e2af", "green": "#a6e3a1",
        "teal": "#94e2d5", "sky": "#89dceb", "sapphire": "#74c7ec",
        "blue": "#89b4fa", "lavender": "#b4befe", "text": "#cdd6f4",
        "subtext1": "#bac2de", "subtext0": "#a6adc8", "overlay2": "#9399b2",
        "overlay1": "#7f849c", "overlay0": "#6c7086", "surface2": "#585b70",
        "surface1": "#45475a", "surface0": "#313244", "base": "#1e1e2e",
        "mantle": "#181825", "crust": "#11111b",
    },
}


def render(palette_name: str) -> str:
    p = PALETTES[palette_name]
    return f"""\
# Generated by build-plugin-theme.py — DO NOT EDIT.
# Regenerated by `ewallis-theme` on every palette switch.
# Palette: catppuccin_{palette_name}

# ─── zsh-autosuggestions ─────────────────────────────────────────────────────
# Ghost-text completion uses overlay0 — visible but subdued.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg={p["overlay0"]}'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# ─── zsh-syntax-highlighting (Catppuccin {palette_name}) ─────────────────────
# Must be defined BEFORE zsh-syntax-highlighting.zsh is sourced.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg={p["text"]}'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={p["red"]}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={p["mauve"]}'
ZSH_HIGHLIGHT_STYLES[alias]='fg={p["teal"]}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={p["teal"]}'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg={p["teal"]}'
ZSH_HIGHLIGHT_STYLES[builtin]='fg={p["teal"]}'
ZSH_HIGHLIGHT_STYLES[function]='fg={p["blue"]}'
ZSH_HIGHLIGHT_STYLES[command]='fg={p["green"]}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={p["green"]},italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={p["pink"]}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg={p["green"]}'
ZSH_HIGHLIGHT_STYLES[path]='fg={p["text"]}'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg={p["pink"]}'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg={p["text"]}'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={p["yellow"]}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={p["mauve"]}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={p["peach"]}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={p["peach"]}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={p["mauve"]}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={p["yellow"]}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={p["yellow"]}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={p["yellow"]}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg={p["lavender"]}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg={p["lavender"]}'
ZSH_HIGHLIGHT_STYLES[assign]='fg={p["text"]}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={p["pink"]}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={p["overlay1"]},italic'
ZSH_HIGHLIGHT_STYLES[arg0]='fg={p["green"]}'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg={p["red"]}'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg={p["yellow"]}'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg={p["green"]}'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg={p["blue"]}'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg={p["mauve"]}'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg={p["pink"]}'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg={p["base"]},bg={p["rosewater"]}'

# ─── fzf (Catppuccin {palette_name}) ─────────────────────────────────────────
# Prepended to any existing FZF_DEFAULT_OPTS the user has set.
_EWALLIS_FZF_COLORS="\\
--color=bg+:{p["surface0"]},bg:{p["base"]},spinner:{p["rosewater"]},hl:{p["red"]} \\
--color=fg:{p["text"]},header:{p["red"]},info:{p["mauve"]},pointer:{p["rosewater"]} \\
--color=marker:{p["lavender"]},fg+:{p["text"]},prompt:{p["mauve"]},hl+:{p["red"]} \\
--color=selected-bg:{p["surface1"]} \\
--color=border:{p["surface2"]},label:{p["text"]}"
export FZF_DEFAULT_OPTS="$_EWALLIS_FZF_COLORS ${{FZF_DEFAULT_OPTS:-}}"
unset _EWALLIS_FZF_COLORS
"""


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    palette, out = sys.argv[1], Path(sys.argv[2])
    if palette not in PALETTES:
        raise SystemExit(f"unknown palette: {palette!r}")
    out.write_text(render(palette), encoding="utf-8")
    print(f"  wrote {out}")


if __name__ == "__main__":
    main()
