# Generated by build-plugin-theme.py — DO NOT EDIT.
# Regenerated by `ewallis-theme` on every palette switch.
# Palette: catppuccin_mocha

# ─── zsh-autosuggestions ─────────────────────────────────────────────────────
# Ghost-text completion uses overlay0 — visible but subdued.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#6c7086'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# ─── zsh-syntax-highlighting (Catppuccin mocha) ─────────────────────
# Must be defined BEFORE zsh-syntax-highlighting.zsh is sourced.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#cdd6f4'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#f38ba8'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#cba6f7'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#94e2d5'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#94e2d5'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#94e2d5'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#94e2d5'
ZSH_HIGHLIGHT_STYLES[function]='fg=#89b4fa'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a6e3a1'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#a6e3a1,italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#f5c2e7'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#a6e3a1'
ZSH_HIGHLIGHT_STYLES[path]='fg=#cdd6f4'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#f5c2e7'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#cdd6f4'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#f9e2af'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#cba6f7'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#fab387'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#fab387'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#cba6f7'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#f9e2af'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#f9e2af'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#f9e2af'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#b4befe'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#b4befe'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#cdd6f4'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#f5c2e7'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#7f849c,italic'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#a6e3a1'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#f38ba8'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=#f9e2af'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=#a6e3a1'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=#89b4fa'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=#cba6f7'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg=#f5c2e7'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg=#1e1e2e,bg=#f5e0dc'

# ─── fzf (Catppuccin mocha) ─────────────────────────────────────────
# Prepended to any existing FZF_DEFAULT_OPTS the user has set.
_EWALLIS_FZF_COLORS="\
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--color=selected-bg:#45475a \
--color=border:#585b70,label:#cdd6f4"
export FZF_DEFAULT_OPTS="$_EWALLIS_FZF_COLORS ${FZF_DEFAULT_OPTS:-}"
unset _EWALLIS_FZF_COLORS
