# Generated by build-plugin-theme.py — DO NOT EDIT.
# Regenerated by `ewallis-theme` on every palette switch.
# Palette: catppuccin_latte

# ─── zsh-autosuggestions ─────────────────────────────────────────────────────
# Ghost-text completion uses overlay0 — visible but subdued.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#9ca0b0'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# ─── zsh-syntax-highlighting (Catppuccin latte) ─────────────────────
# Must be defined BEFORE zsh-syntax-highlighting.zsh is sourced.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#4c4f69'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#d20f39'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#8839ef'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#179299'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#179299'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#179299'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#179299'
ZSH_HIGHLIGHT_STYLES[function]='fg=#1e66f5'
ZSH_HIGHLIGHT_STYLES[command]='fg=#40a02b'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#40a02b,italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#ea76cb'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#40a02b'
ZSH_HIGHLIGHT_STYLES[path]='fg=#4c4f69,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#ea76cb'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#4c4f69,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#df8e1d'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#8839ef'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#fe640b'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#fe640b'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#8839ef'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#df8e1d'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#df8e1d'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#df8e1d'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#7287fd'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#7287fd'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#4c4f69'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#ea76cb'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#8c8fa1,italic'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#40a02b'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#d20f39'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=#df8e1d'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=#40a02b'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=#1e66f5'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=#8839ef'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg=#ea76cb'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg=#eff1f5,bg=#dc8a78'

# ─── fzf (Catppuccin latte) ─────────────────────────────────────────
# Prepended to any existing FZF_DEFAULT_OPTS the user has set.
_EWALLIS_FZF_COLORS="\
--color=bg+:#ccd0da,bg:#eff1f5,spinner:#dc8a78,hl:#d20f39 \
--color=fg:#4c4f69,header:#d20f39,info:#8839ef,pointer:#dc8a78 \
--color=marker:#7287fd,fg+:#4c4f69,prompt:#8839ef,hl+:#d20f39 \
--color=selected-bg:#bcc0cc \
--color=border:#acb0be,label:#4c4f69"
export FZF_DEFAULT_OPTS="$_EWALLIS_FZF_COLORS ${FZF_DEFAULT_OPTS:-}"
unset _EWALLIS_FZF_COLORS
