# Generated by build-plugin-theme.py — DO NOT EDIT.
# Regenerated by `ewallis-theme` on every palette switch.
# Palette: catppuccin_macchiato

# ─── zsh-autosuggestions ─────────────────────────────────────────────────────
# Ghost-text completion uses overlay0 — visible but subdued.
# NOTE: ZSH_AUTOSUGGEST_STRATEGY is set by the managed .zshrc block (gated on
# the `ew predict-off` flag), NOT here — so a theme switch never re-enables it.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#6e738d'

# ─── zsh-syntax-highlighting (Catppuccin macchiato) ─────────────────────
# Must be defined BEFORE zsh-syntax-highlighting.zsh is sourced.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#cad3f5'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#ed8796'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#c6a0f6'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#8bd5ca'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#8bd5ca'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#8bd5ca'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#8bd5ca'
ZSH_HIGHLIGHT_STYLES[function]='fg=#8aadf4'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a6da95'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#a6da95,italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#f5bde6'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#a6da95'
ZSH_HIGHLIGHT_STYLES[path]='fg=#cad3f5'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#f5bde6'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#cad3f5'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#eed49f'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#c6a0f6'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#f5a97f'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#f5a97f'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#c6a0f6'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#eed49f'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#eed49f'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#eed49f'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#b7bdf8'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#b7bdf8'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#cad3f5'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#f5bde6'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#8087a2,italic'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#a6da95'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#ed8796'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=#eed49f'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=#a6da95'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=#8aadf4'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=#c6a0f6'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg=#f5bde6'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg=#24273a,bg=#f4dbd6'

# ─── fzf (Catppuccin macchiato) ─────────────────────────────────────────
# Prepended to any existing FZF_DEFAULT_OPTS the user has set.
_EWALLIS_FZF_COLORS="\
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#b7bdf8,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--color=selected-bg:#494d64 \
--color=border:#5b6078,label:#cad3f5"
export FZF_DEFAULT_OPTS="$_EWALLIS_FZF_COLORS ${FZF_DEFAULT_OPTS:-}"
unset _EWALLIS_FZF_COLORS

# ─── fzf-tab (Catppuccin macchiato) ─────────────────────────────────────
# Colors the group headers of the fzf-tab Tab menu. Read lazily at Tab-press,
# so this is fine to set after fzf-tab was sourced. No-op if fzf-tab absent.
zstyle ':fzf-tab:*' group-colors \
  '#c6a0f6' '#8aadf4' '#a6da95' '#f5a97f' \
  '#8bd5ca' '#f5bde6' '#eed49f' '#7dc4e4'
zstyle ':fzf-tab:*' prefix ''
