# Generated by build-plugin-theme.py — DO NOT EDIT.
# Regenerated by `ewallis-theme` on every palette switch.
# Palette: catppuccin_frappe

# ─── zsh-autosuggestions ─────────────────────────────────────────────────────
# Ghost-text completion uses overlay0 — visible but subdued.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#737994'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# ─── zsh-syntax-highlighting (Catppuccin frappe) ─────────────────────
# Must be defined BEFORE zsh-syntax-highlighting.zsh is sourced.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#c6d0f5'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#e78284'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#ca9ee6'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#81c8be'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#81c8be'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#81c8be'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#81c8be'
ZSH_HIGHLIGHT_STYLES[function]='fg=#8caaee'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a6d189'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#a6d189,italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#f4b8e4'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#a6d189'
ZSH_HIGHLIGHT_STYLES[path]='fg=#c6d0f5,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#f4b8e4'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#c6d0f5,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#e5c890'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#ca9ee6'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#ef9f76'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#ef9f76'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#ca9ee6'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#e5c890'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#e5c890'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#e5c890'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#babbf1'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#babbf1'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#c6d0f5'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#f4b8e4'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#838ba7,italic'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#a6d189'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#e78284'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=#e5c890'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=#a6d189'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=#8caaee'
ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=#ca9ee6'
ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg=#f4b8e4'
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='fg=#303446,bg=#f2d5cf'

# ─── fzf (Catppuccin frappe) ─────────────────────────────────────────
# Prepended to any existing FZF_DEFAULT_OPTS the user has set.
_EWALLIS_FZF_COLORS="\
--color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284 \
--color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
--color=marker:#babbf1,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284 \
--color=selected-bg:#51576d \
--color=border:#626880,label:#c6d0f5"
export FZF_DEFAULT_OPTS="$_EWALLIS_FZF_COLORS ${FZF_DEFAULT_OPTS:-}"
unset _EWALLIS_FZF_COLORS
