# >>> ewallis-terminal >>>
# Managed block — do not edit between these markers.
# Anything inside is overwritten on reinstall and on `ewallis-theme` switches.
# Put YOUR customizations AFTER the closing marker.
# Remove with: /usr/local/share/ewallis-terminal/bin/ewallis-terminal-uninstall
_EWALLIS_PKG_ROOT="/usr/local/share/ewallis-terminal"
_EWALLIS_PLUGINS="$_EWALLIS_PKG_ROOT/plugins"

# 1. zsh-autosuggestions — ghost-text history completion (must be before s-h)
#    Guard: skip if user already has it loaded via oh-my-zsh, brew, etc.
if [[ -r "$_EWALLIS_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] \
   && (( ! $+functions[_zsh_autosuggest_start] )); then
  source "$_EWALLIS_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

# 2. fzf — bindings + completion (binary not vendored; comes via brew)
#    We cache `brew --prefix fzf` in ~/.config/ewallis-terminal/fzf-prefix to
#    avoid paying ~80ms on every shell startup.
if command -v fzf >/dev/null 2>&1; then
  if [[ -r "$HOME/.config/ewallis-terminal/fzf-prefix" ]]; then
    _ewallis_fzf_prefix="$(<$HOME/.config/ewallis-terminal/fzf-prefix)"
    [[ -r "$_ewallis_fzf_prefix/shell/key-bindings.zsh" ]] && \
      source "$_ewallis_fzf_prefix/shell/key-bindings.zsh"
    [[ -r "$_ewallis_fzf_prefix/shell/completion.zsh" ]] && \
      source "$_ewallis_fzf_prefix/shell/completion.zsh"
    unset _ewallis_fzf_prefix
  fi
fi

# 3. Starship prompt
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi

# 4. ESC-ESC context-aware widget:
#       buffer empty  → open session history picker (fzf)
#       buffer dirty  → clear the line (legacy behavior)
#    Session = commands typed since this shell started. We record the starting
#    HISTCMD now (after history file has been loaded) so the picker can show
#    only the deltas, not the full ~/.zsh_history.
typeset -g _EWALLIS_HIST_START=$HISTCMD

_ewallis_history_picker() {
  command -v fzf >/dev/null 2>&1 || { zle reset-prompt; return; }

  # Reverse on macOS = `tail -r`; on Linux = `tac`. Pick whichever exists.
  local reverse="tail -r"
  command -v tac >/dev/null 2>&1 && reverse="tac"

  # Build list: session commands, deduped, newest first, capped at 50.
  local selected
  selected="$(
    fc -ln "$_EWALLIS_HIST_START" 2>/dev/null \
      | awk 'NF && !seen[$0]++' \
      | eval "$reverse" \
      | head -n 50 \
      | fzf --height=40% --layout=reverse --border=rounded \
            --prompt='history > ' \
            --header='ESC cancel  ·  Enter load into prompt' \
            --no-multi --no-sort 2>/dev/null
  )"
  if [[ -n "$selected" ]]; then
    BUFFER="$selected"
    CURSOR=${#BUFFER}
  fi
  zle reset-prompt
}
zle -N _ewallis_history_picker

_ewallis_esc_handler() {
  if [[ -z "$BUFFER" ]]; then
    _ewallis_history_picker
  else
    BUFFER=""
    CURSOR=0
  fi
}
zle -N _ewallis_esc_handler
bindkey '\e\e' _ewallis_esc_handler

# 5. Palette-aware theming (sets ZSH_HIGHLIGHT_STYLES / autosuggest / fzf colors)
#    Regenerated by `ewallis-theme` on every palette switch.
if [[ -r "$HOME/.config/ewallis-terminal/plugin-theme.zsh" ]]; then
  source "$HOME/.config/ewallis-terminal/plugin-theme.zsh"
fi

# 6. zsh-syntax-highlighting — MUST be sourced last
#    Guard: skip if user already has it loaded via oh-my-zsh, brew, etc.
if [[ -r "$_EWALLIS_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] \
   && (( ! $+functions[_zsh_highlight] )); then
  source "$_EWALLIS_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# 7. Doctor nag — silent if all deps satisfied
if [[ -f "$HOME/.local/share/ewallis-terminal/needs-doctor" ]]; then
  print -P -- "%F{214}!%f ewallis-terminal: missing deps. Run: %F{141}ewallis-terminal-doctor%f"
fi

# 8. Welcome banner — shows once per top-level interactive shell.
#    Guards:
#      • interactive only      (-o interactive)
#      • not already shown     ($EWALLIS_BANNER_SHOWN is exported so subshells
#                               inherit it and skip the banner)
#      • not opted-out         (set EWALLIS_NO_BANNER=1 to disable globally)
#    Disable per-shell:  EWALLIS_NO_BANNER=1 zsh
#    Disable for good:   add `export EWALLIS_NO_BANNER=1` AFTER this block
if [[ -o interactive ]] \
  && [[ -z "${EWALLIS_BANNER_SHOWN:-}" ]] \
  && [[ -z "${EWALLIS_NO_BANNER:-}" ]] \
  && [[ ! -f "$HOME/.config/ewallis-terminal/banner.disabled" ]]; then
  export EWALLIS_BANNER_SHOWN=1
  if [[ -x "$_EWALLIS_PKG_ROOT/bin/ewallis-welcome" ]]; then
    "$_EWALLIS_PKG_ROOT/bin/ewallis-welcome" 2>/dev/null
  fi
fi

unset _EWALLIS_PKG_ROOT _EWALLIS_PLUGINS
# <<< ewallis-terminal <<<
